[build]
  command = "npm run build:netlify"
  ignore = "frameit/**"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  PRISMA_GENERATE_DATAPROXY = "false"
